---
language: node_js
node_js:
  - "stable"

sudo: false

cache:
  directories:
    - ember/node_modules
    - ember/bower_components

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - cd ember
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

notifications:
  email:
    on_success: never
