# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wes Moberly - Freelance Web Developer & Consultant
email: wesm87@gmail.com
description: > # this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wesmoberly.me" # the base hostname & protocol for your site
twitter_username: wesm87
github_username:  wesm87

# Permalinks
permalink: pretty

# Build settings
markdown: kramdown
incremental: true

exclude:
  - node_modules
  - package.json
  - gulpfile.js
  - gulpfile.coffee

# Sass settings
sass:
  sass_dir: assets/css/src
  style: compressed

# Plugin configuration
jekyll_timeago:
  prefix: 'Posted'
